# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bd96e91beee2c92c3e078acd723ea4f2514cf5a9f91443f0c35871eab6e6cb9a06b01b5f94bbae3c82ee9e70fbffa766b36de75616c7b36f9416c178c08420b

test:
  secret_key_base: a0c936dea1cfc4fdf9ac4010307fae22c522cf1017da107eee302121732c56db54775e9afff89518cbbd514bedab3a49d67544a5dfb8bde2f319e46fa70e1fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
